server:
  port: ${SERVER_PORT:8091}

spring:
  application:
    name: document-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/document_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  cloud:
    vault:
      enabled: true
      uri: ${VAULT_URI:http://localhost:8200}
      token: ${VAULT_TOKEN:root}
      kv:
        enabled: false

application:
  security:
    jwt:
      issuer: ${JWT_ISSUER:identity-service}
      key-name: ${JWT_KEY_NAME:identity-service-jwt-ed25519}

  messaging-service:
    base-url: ${MESSAGING_SERVICE_BASE_URL:http://localhost:8087}
    chat-path: ${MESSAGING_SERVICE_CHAT_PATH:/api/v1/chats/{chatId}}
    current-chats-path: ${MESSAGING_SERVICE_CURRENT_CHATS_PATH:/api/v1/chats}

  identity-service:
    base-url: ${IDENTITY_SERVICE_BASE_URL:http://localhost:8085}
    internal-device-path: ${IDENTITY_SERVICE_INTERNAL_DEVICE_PATH:/api/v1/devices/{deviceId}/internal}

logging:
  level:
    dev.documentservice: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
