spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    vault:
      uri: ${VAULT_URI}
      token: ${VAULT_TOKEN}

application:
  identity-service:
    base-url: ${IDENTITY_SERVICE_BASE_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  outbox:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    org.springframework.data.repository.config: WARN
    org.springframework.data.redis.repository.configuration: WARN
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    dev.messagingservice: INFO
    org.springframework.kafka: WARN
