spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:2s}
    repositories:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/media_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  cloud:
    vault:
      enabled: true
      uri: ${VAULT_URI:http://localhost:8200}
      token: ${VAULT_TOKEN:root}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.data.repository.config: WARN
    org.springframework.data.redis.repository.configuration: WARN
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    dev.mediaservice: DEBUG
