package dev.cryptoservice.model.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

@Schema(description = "Request DTO for registering device identity public key.")
public record RegisterIdentityKeyRequestDto(
    @NotNull(message = "Registration ID can't be empty.")
    @Positive(message = "Registration ID must be positive.")
    @Schema(description = "Signal registration ID generated by the local device.")
    Integer registrationId,

    @NotBlank(message = "Public key can't be empty.")
    @Size(max = 10000, message = "Public key is too long.")
    @Schema(description = "Serialized public identity key.")
    String publicKey
) {}
