spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/identity_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  cloud:
    vault:
      enabled: true
      uri: ${VAULT_URI:http://localhost:8200}
      token: ${VAULT_TOKEN:root}

application:
  initial-admin:
    enabled: ${INITIAL_ADMIN_ENABLED:true}

  outbox:
    enabled: ${OUTBOX_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    dev.identityservice: DEBUG
