spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:2s}
    repositories:
      enabled: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/identity_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  cloud:
    vault:
      enabled: true
      uri: ${VAULT_URI:http://localhost:8200}
      token: ${VAULT_TOKEN:root}

application:
  rate-limit:
    enabled: true
    key-prefix: ${RATE_LIMIT_KEY_PREFIX:vector:identity:rate-limit}
    requests-per-window: ${RATE_LIMIT_REQUESTS_PER_WINDOW:120}
    window: ${RATE_LIMIT_WINDOW:PT1M}

  initial-admin:
    enabled: ${INITIAL_ADMIN_ENABLED:true}

  outbox:
    enabled: ${OUTBOX_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.springframework.data.repository.config: WARN
    org.springframework.data.redis.repository.configuration: WARN
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    dev.identityservice: DEBUG
