package dev.realtimegateway.model.enumeration;

public enum RealtimeEventType {
    MESSAGE_CREATED,
    MESSAGE_DELIVERED,
    MESSAGE_READ,
    CHAT_UPDATED,
    TYPING,
    PRESENCE_UPDATED,
    PRESENCE_SNAPSHOT,
    DOCUMENT_CREATED,
    DOCUMENT_UPDATED,
    DOCUMENT_SIGNED,
    DOCUMENT_REJECTED,
    DOCUMENT_CANCELLED,
    DOCUMENT_HIDDEN,
    DOCUMENT_OBSERVERS_ADDED,
    PROFILE_UPDATED,
    DEVICE_REVOKED
}
