package dev.identityservice.common.error;

public enum ErrorCode {
    ACCESS_DENIED,
    ACCOUNT_ALREADY_EXISTS,
    ACCOUNT_BLOCKED,
    ACCOUNT_NOT_FOUND,
    AUTHENTICATION_FAILED,
    DEVICE_NOT_FOUND,
    DEVICE_REGISTRATION_FAILED,
    DEVICE_REVOKED,
    INVALID_REFRESH_TOKEN,
    INVALID_REGISTRATION_TOKEN,
    PASSWORD_CONFIRMATION_MISMATCH,
    REGISTRATION_ALREADY_COMPLETED,
    REGISTRATION_EXPIRED,
    REGISTRATION_NOT_FOUND,
    TOKEN_SIGNING_FAILED,
    VALIDATION_FAILED,
    INTERNAL_SERVER_ERROR
}
