spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:2s}
    repositories:
      enabled: false
  cloud:
    vault:
      enabled: ${VAULT_ENABLED:true}
      uri: ${VAULT_URI}
      token: ${VAULT_TOKEN}

application:
  websocket:
    allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    dev.realtimegateway: INFO
