services:
  realtime-redis:
    image: redis:8
    container_name: realtime-redis
    ports:
      - "6383:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - realtime-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  realtime-redis-data:
